name: Terraform Release Pipeline

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: "AWS Access Key ID"
        required: true
      aws_secret_access_key:
        description: "AWS Secret Access Key"
        required: true
      aws_session_token:
        description: "AWS Session Token"
        required: true
      aws_region:
        description: "AWS Region"
        required: true
        default: "us-east-1"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change to iac directory
        run: cd iac

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Terraform Init
        working-directory: ./iac
        run: terraform init

      - name: Terraform Plan
        working-directory: ./iac
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./iac
        run: terraform apply --auto-approve
